### PR TITLE
support empty file type

### PR DESCRIPTION
**Pull request by amitport**

### CODE REVIEW

**Comment by AckerApple** [comment]
Are you saying to support accept="" ? Please elaborate. These 0 detail issue reports are a hard swallow at first. I would so prefer you post a picture of your favorite hobby than to leave absolutely nothing.

I wont touch this issue without further details

**Comment by amitport** [comment]
- `accept=".mxf,video/*"`
- when native file browser open I select an mxf file. 
- in your `acceptFilter`: `file.type === '' ` and `file.name` is `<my-file>.mxf`

(BTW as a workaround I just add the files from `lastInvalidsChange` event)

**Comment by AckerApple** [comment]
I got you.

The file names are not available during drag but I don't think you are even doing drag/drop being that you mention the word "native".

A FIX IS NEEDED: On selecting or dropping files, this library needs to take into consideration the available file names

**Comment by AckerApple** [comment]
Please acquire version 0.3.5 . Test and close issue if to your satisfaction.

Your unit test for this issue is here:
https://github.com/AckerApple/angular-file/blob/development/src/file-upload/FileUploader.class.spec.ts#L27

**Comment by AckerApple** [comment]
yooooooooooooooooo, I'm so sorry. I didn't see this was a pull request.

I'm so kicking myself

**Comment by AckerApple** [comment]
Thank you for issuing a pull request. I'm so over thankful that I'm kicking myself for thinking it was another issue report with no details.

Please use my 0.3.5 as I would have rejected this pull request anyhow. Check my fix out and let me know if I covered your issue

**Pull request closed without merging**
