### PR TITLE
Build against angular@10.0.0

### PR DESCRIPTION
**Pull request by Betalos**

### CODE REVIEW

**Comment by AckerApple** [comment]
Oh wow ng 10 is a thing now. Ok I’ll get to this within a few days

**Comment by Betalos** [comment]
@AckerApple yeah they're working fast, ng9 was just dropped like a 3 months ago.

**Comment by AckerApple** [comment]
Put my two weeks in at work. I will now have time for this certainly, lol.

Know of any developer job openings?

**Comment by Betalos** [comment]
@AckerApple well from the back of my head I don't know of any opening, but I'll keep in mind if something pops up

**Comment by AckerApple** [comment]
Hey @Betalos I've not had merge conflicts from forks before. I tried to solve using the github provided instructions but could not solve. Could you please lend a hand?

**Comment by Betalos** [comment]
Hi @AckerApple, OK pal I'll try to fix it

**Comment by AckerApple** [comment]
HEY I forgot about this. I’ll try to check on it this weekend. Provide status update if one worth giving. Thank you

**Comment by Betalos** [comment]
Hello @AckerApple.
I'm so sorry I totally forget about this (I got caught up in some work).
Well I'll try to resolve the issue ASAP.

**Comment by Betalos** [comment]
Hi @AckerApple, Well I tried to fix the issue but the thing is I am not allowed to change in the main repo.
What I am suggesting is you just accept my changes when resolving the conflict.
Those files would be regenrated any way.

**Comment by PowerKiKi** [comment]
Why does this package have distribution files in two different places ? once in `dist/` of branch `develop` and once in root of branch `master` ?

That seems very conflict prone for every single PR. I wouldn't keep distribution files in git at all. But at the very worst keeping them only on master would really help to review and merge PR more easily.

**Comment by AckerApple** [comment]
The develop branch is where us coders work and I don’t git ignore the dist for personal preference.

The master branch is what is published to npm. Also you can npm install the GitHub version without getting the development files.

**Comment by AckerApple** [comment]
Just built for ng11 and push as version 3.3.0

**Pull request closed without merging**
