### PR TITLE
fixed type for 'file'

### PR DESCRIPTION
**Pull request by adventmedia**
Stricter typing with current version of typescript breaks ngfDrop directive; parameter `file: File` is by definition null at the beginning until a file is dropped. Simple fix.

### CODE REVIEW

**Comment by AckerApple** [comment]
You'll need to make this change in the source file, not the distributed file

https://github.com/AckerApple/angular-file/blob/development/src/file-upload/ngf.directive.ts#L40

Let me know when you have done that and I can pull the source branch and build and deploy

**Comment by AckerApple** [comment]
Before you fork you need to change your branch
image

**Comment by adventmedia** [comment]
I did fork from master branch - just tried again, same result.

￼

Andrew Leith Macrae
Advent Media
Interactive Application Development
1008-720 Spadina Ave
Toronto ON CA M5S 2T9
416.966.3147
Skype: andrewmacrae
adventmedia.net

**Comment by AckerApple** [comment]
Had to look it up, it's when you create the fork you need to uncheck a checkbox
image

**Comment by adventmedia** [comment]
It looks like I should be pulling from development branch, not master:

￼
Andrew Leith Macrae
1008-720 Spadina Ave
Toronto ON CA M5S 2T9
416.966.3147

**Pull request closed without merging**
